package com.hisense.hibeans.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hisense.hibeans.bot.model.BotMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOT_MESSAGE".
*/
public class BotMessageDao extends AbstractDao<BotMessage, Long> {

    public static final String TABLENAME = "BOT_MESSAGE";

    /**
     * Properties of entity BotMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property SendTime = new Property(1, long.class, "sendTime", false, "SEND_TIME");
        public final static Property Direction = new Property(2, int.class, "direction", false, "DIRECTION");
        public final static Property ContentType = new Property(3, int.class, "contentType", false, "CONTENT_TYPE");
        public final static Property Content = new Property(4, String.class, "content", false, "CONTENT");
    }


    public BotMessageDao(DaoConfig config) {
        super(config);
    }
    
    public BotMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOT_MESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"SEND_TIME\" INTEGER NOT NULL ," + // 1: sendTime
                "\"DIRECTION\" INTEGER NOT NULL ," + // 2: direction
                "\"CONTENT_TYPE\" INTEGER NOT NULL ," + // 3: contentType
                "\"CONTENT\" TEXT);"); // 4: content
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOT_MESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BotMessage entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getSendTime());
        stmt.bindLong(3, entity.getDirection());
        stmt.bindLong(4, entity.getContentType());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BotMessage entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getSendTime());
        stmt.bindLong(3, entity.getDirection());
        stmt.bindLong(4, entity.getContentType());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public BotMessage readEntity(Cursor cursor, int offset) {
        BotMessage entity = new BotMessage( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // sendTime
            cursor.getInt(offset + 2), // direction
            cursor.getInt(offset + 3), // contentType
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // content
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BotMessage entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setSendTime(cursor.getLong(offset + 1));
        entity.setDirection(cursor.getInt(offset + 2));
        entity.setContentType(cursor.getInt(offset + 3));
        entity.setContent(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BotMessage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BotMessage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BotMessage entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
