package com.hisense.hibeans.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hisense.hibeans.bot.model.BotMessage;

import com.hisense.hibeans.database.dao.BotMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig botMessageDaoConfig;

    private final BotMessageDao botMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        botMessageDaoConfig = daoConfigMap.get(BotMessageDao.class).clone();
        botMessageDaoConfig.initIdentityScope(type);

        botMessageDao = new BotMessageDao(botMessageDaoConfig, this);

        registerDao(BotMessage.class, botMessageDao);
    }
    
    public void clear() {
        botMessageDaoConfig.clearIdentityScope();
    }

    public BotMessageDao getBotMessageDao() {
        return botMessageDao;
    }

}
